doodle:
  broker:
    client:
      enabled: true
      auto-connected: true

  socket:
    server:
      port: 10001

  login:
    client:
      enabled: true

  payment:
    client:
      enabled: true
